### PR TITLE
Updated the charts to use fewer images.

### PR DESCRIPTION
**Pull request by JayUnt**
Using fewer images to show the charts with greater precision.  This way
if we want to change the chart images we wont need to update 100s of
images.

### CODE REVIEW

**Comment by JayUnt** [comment]
Let me know if im doing this whole fork/pull thing wrong.

**Comment by thadius856** [comment]
Not at all. The fork was correct, and you're the first one to actually Pull Request. If you don't Pull Request, I have to dig into each commit of your fork and it turns into a navigation nightmare. Talk about a PITA!

**Comment by JayUnt** [comment]
Is there anything left on the list for me to work on? I see all of the other issues are assigned or seem to be in progress.

**Comment by thadius856** [comment]
Well, sure. But I'm not sure how much you'll like it.

Between 'these' and 'kemp', they figured out how to both migrate to *SQL and add a tap number column. Unfortunately, that branch is out of sync now with this one, so I can't test and merge automagically. Such is the case with projects where multiple people edit the same files.

To get their work back in, we have to create a new fork, look at their diff, and then manually re-integrate their edits. It shouldn't super hard, but it's something that would take care and diligence.

If you're interested, let me know and I'll both create the issue and assign you. If not, that's cool too.

We can also press forward with additional features, if you have any in mind.

**Comment by JayUnt** [comment]
Yeah i can work on that. We need it to get in the system as some time, so it might as well be now.

**Pull request merged**
