### PR TITLE
Update contributors.php

### PR DESCRIPTION
**Pull request by EmDubeu**
added contribution details.

### CODE REVIEW

**Comment by thadius856** [comment]
Resubmit pull request against `develop` branch. :)

**Comment by EmDubeu** [comment]
Gauhhhhh, wrong branch...

On Sun, Feb 9, 2014 at 10:29 PM, thadius856 notifications@github.comwrote:

> Resubmit pull request against develop branch. :)
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/pull/131#issuecomment-34603932
> .

## 

Mike Wright

**Comment by thadius856** [comment]
If you're having trouble, here's an easy way to do it:

TortoiseGit > Switch/Checkout
Choose the `develop` branch. Click Ok, then Ok again.
TortoiseGit > Merge. In the "From" box, select your branch (`EmDebeu:patch-1`).
Click Ok.
You may have to Commit, but it probably already did it for you.

If it doesn't give you an option to "Create Pull Request", you may have to Commit again, but select "Amend last commit" and don't change the message.

**Comment by sevlabs** [comment]
I need to add my info to contributors.php as well. When I run 
'TortoiseGit' -> 'Pull' to update my local copy with the latest updates, 
will it bring my copy current with the most recent development changes 
on GitHub?  I tried exactly that and it didn't seem to work.

**Comment by thadius856** [comment]
Yes, that is what Pull does.

You need to Switch/Checkout to `develop`. And you need to be sure you pull the remote branch `develop` into your local branch `develop`.

**Comment by thadius856** [comment]
Note, Ekim's isn't in yet because he hasn't pushed to `develop` yet, so you won't see his info.

**Comment by sevlabs** [comment]
What's the difference between "staffers" and "special thanks to" sections on the contributors.php page? I'd like to add my untappd handle like the "staffers" have... but the special thanks to folks only have HBT and GitHub columns.

**Comment by thadius856** [comment]
Staffs are semi-permanent. Special thanks are people who contribute a feature or two, and are probably transient. The only real difference is Staffers get to pick their own title. Woo! :P

Feel free to add an uptapped column to the Special Thanks section. There's no reason it can't be there.

Do you plan on sticking around for a while?

**Comment by sevlabs** [comment]
I'd be happy to stick around if you guys can tolerate my constant questions about GitHub how-to!

**Comment by thadius856** [comment]
Might as well add a Untapped column to the bottom and throw yourself up top then.

**Comment by sevlabs** [comment]
I updated contributors; added myself and EmDubeu ... pushed to develop 
branch.

**Pull request closed without merging**
