### PR TITLE
Initial pull for feature-bottles

### PR DESCRIPTION
**Pull request by dlgreenwald**
I fixed 2, 3, and 4, and think I fixed 5 unintentionally at least if I understand what your saying. I'll put a pull request in for the branch you named here shortly.

As for 1: I only pulled the fields that really didn't make any since to me. I agree with most of your fields and am indifferent to the others and could see them being useful for some people

As for 6: totally agree, but for the record I suck at UCD and was taking the fastest path forward. It could be that just removing the logo's is actually whats appropriate.

Would you like me to continue developing in my own repo and issuing pull requests on occasion?

### CODE REVIEW

**Comment by thadius856** [comment]
That's our preferred method. :)

@Skemp45, I'll let you look this one over since you're already familiar with it.

**Comment by JayUnt** [comment]
You are going to need to make another sql file that is just your updates to the schema/inserts.  When we push this, we are not going to be able to have the user just re-run schema.sql because it will delete all of their data that the are putting in.

Unfortunately we don't have a convention yet for this, but you are lucky to be the first new feature that requires a schema change. I say for now, do this:
- Inside the install folder, make a new folder called updates
- Inside updates make a file called "1 feature-bottles.sql"
- Put your config insert and table create in there

The 1 in the file name is to keep the scripts in order, so when there are more scripts, we know that this one should be run first.

Or we can have another inside updates called updates.php that only has an array.  And when you add an update script, you add the your filename to that array

Thad, Skemp, Anyone,
What do you think about the sql update location/name?

**Comment by JayUnt** [comment]
Thinking about it a bit more, we are going to want to associate these update files with the version number they are going in with.  So maybe inside updates we have a folder that is named with the version number that the update is going to go out with.  So each version will have its own update folder.  Then inside there we can either name the files with a number a the beginning, or each can have their own file with an array in it.

**Comment by Skemp45** [comment]
Yeah, that sounds like a good way to stay organized

**Comment by thadius856** [comment]
Cool.

**Comment by Skemp45** [comment]
I still see some bugs but lets go ahead and pull this into the bottles branch so we can all work at it

**Comment by dlgreenwald** [comment]
How do you want to handle database work like this where it isn't slated for a feature release yet?  I could just make 2.0 folder in the updates directory but that seems quite presumptuous of me.  

I actually agree with the organization proposed for things that are known to tie to a specific release, I just think that most things will start out not tied to a specific release and will then be dropped into one.

**Comment by Skemp45** [comment]
closing to clean up issue board and get project back on task

**Pull request closed without merging**
