### PR TITLE
Show beer available in bottles as well as kegs

### PR DESCRIPTION
**Pull request by dlgreenwald**
I followed the DB patterns used for kegs and expanded the functionality to include bottles available on "shelves" in your fridge.

### CODE REVIEW

**Comment by Skemp45** [comment]
This should not be merged just yet. I downloaded it and installed it and there are quite a few bugs. How about we make a branch for it and work on it in the branch, not in the master,

**Comment by dlgreenwald** [comment]
Fine by me. If you give me details on the bugs you found I'll stomp on them.  —

**Comment by thadius856** [comment]
Have not tested, but anything requiring DB changes is too big for a hotfix. Agree this would be better to throw into the develop stream for incorporation into a future minor version.

@dlgreenwald I've created and pushed a new branch for you: `feature-bottles`. Please re-submit Pull Request against that branch, and we'll gladly take a look.

**Comment by Skemp45** [comment]
Bug 1
When adding bottle it uses label which does not make sense for a bottle then stamped owner and stamped location should not really be an option, then status does not make sense for a bottle. Here is what I am thinking, and please let me know what you think :D 

```
Name:
Style:
Brewery:
ABV:
Amount:
```

Keep it simple. 

Bug 2 

when on the bottle_form.php hitting cancel taks you back to keg list not my bottles.

Bug 3
Deleting a bottle from the bottle list give a message of Keg successfully deleted, should say bottle.

Bug 4
When putting a bottle on the shelf if you hit cancel it takes you to the tap list instead of my shelves

Bug 5
When trying to put a beer on the shelf the Beer dropdown pulls from the my beers section and does not show the added bottles just the kegs of beer. 

Bug 6
More of a suggestion than a bug-

I think instead of replicating the raspberrypints and your Logo Here image we should have a new header called Bottle List or something. Or even have a button in the admin panel that says use bottles or use kegs. and have one or the other but not both. Just a suggestion

**Comment by Skemp45** [comment]
But for real, Nice work man!!!

**Comment by dlgreenwald** [comment]
I fixed 2, 3,  and 4, and _think_ I fixed 5 unintentionally at least if I understand what your saying.  I'll put a pull request in for the branch you named here shortly.  

As for 1: I only pulled the fields that really didn't make any since to me.  I agree with most of your fields and am indifferent to the others and could see them being useful for some people

As for 6: totally agree, but for the record I suck at UCD and was taking the fastest path forward.  It could be that just removing the logo's is actually whats appropriate.

Would you like me to continue developing in my own repo and issuing pull requests on occasion?

**Pull request closed without merging**
