### PR TITLE
Update schema.sql

### PR DESCRIPTION
**Pull request by mcangeli**
Updated untID field in Beers table to have a default value of 0

### CODE REVIEW

**Comment by JayUnt** [comment]
Are you keeping track of these schema changes in another alter script? We
will need them when people update their already setup system.

**Comment by thadius856** [comment]
We can diff `schema.sql` against previous releases using their release candidate branches, as long as we don't delete them. It may be possible to compare directly to a release too, but I haven't tried yet.

**Comment by thadius856** [comment]
Maybe nitpicking here, but why NOT NULL DEFAULT 0? NULL seems to much easier, and doesn't require an input on the beers form.

**Comment by JayUnt** [comment]
And we would create the alter scripts using the diffs? This seems student then what we were discussing with the update process.  I just don't want these to get lost too.

And I agree, if its nullable, then it doesn't need a default. To me null is better than 0 for if there is no value.

**Comment by thadius856** [comment]
> And we would create the alter scripts using the diffs?

Yes. Ex: https://github.com/RaspberryPints/RaspberryPints/compare/feature-flow_monitor...hotfix-1.0.2?expand=1

Student?

**Comment by JayUnt** [comment]
... im not sure i see what you are trying to show me.  I know we can merge, but with the sql its not going to be a matter of merging.  For instance with the flow_sensor release, i created a new sql file.  This file assumes that the database is set.  I am moving a lot of fields from the taps table to the batches table.  So after i create the batches table and move the user's existing data, i have some scripts to drop those no longer used columns from taps. Like this:

```
ALTER TABLE taps DROP COLUMN `beerId`;
ALTER TABLE taps DROP COLUMN `kegId`;
```

This would be a pain for you to figure out  at the time of the release, especially moving the data around.  But we can't just have it in schema because then the users would have to drop schema and lose all of their data.  But if i just removed that row from the taps table create, you would really be screwed.  See what im saying?

**Comment by thadius856** [comment]
> ... im not sure i see what you are trying to show me.

If you scroll down, you see all the changes in schema.sql.

That's the list of changes you need to turn into a patch. You can diff between the current release and anything you'd like to release.

Is that not what you want?

**Comment by thadius856** [comment]
And I understand what you mean about not wanting to do that regularly.

But since there was no system in place when we started down this road, that's how it'll have to be for the first patch... manually building a patch file from the changes to schema, then revert schema to the release version.

**Comment by mcangeli** [comment]
@thadius856 the current code for the rating checks to see that the untid is something other than 0. 

Honestly, it was quicker for me to update the sql schema than it was for me to edit the code to check for null instead.

if it does an insert to the DB and the untID is not filled in, it should default to 0 and not matter if they didn't fill in the untid field.

**Pull request closed without merging**
