### PR TITLE
Kegerface sql slim

### PR DESCRIPTION
**Pull request by thadius856**
Please grant permission to roll all of these edits back into the Master branch.

### CODE REVIEW

**Comment by thadius856** [comment]
These edits need to be rolled in manually. This branch cannot be merged automagically.

Edits to apply to a new fork: 

https://github.com/thadius856/Digital-Taplist/compare/master...kegerface-SQL-SLIM

Please submit Pull Request when done.

**Comment by Skemp45** [comment]
address this here https://github.com/thadius856/Digital-Taplist/pull/19

**Comment by thadius856** [comment]
Closed due to technical limitations of automatic merging on GitHub.

Created new fork and manually re-applied edits instead.

**Comment by thadius856** [comment]
Well, I tried to get everything go this morning. Still no go.

Can't see the SQL edits in the master branch, main fork. From the master
branch, click "Forks [#]" to see all of them. You can see we have two
forks, plus one extra branch.

Just tried to help from work, but Github is blocked by the corproate
firewall. Lovely.

If you guys can merge everything back and beautiful, go for it. You have
the permissions/rights to perform it. I made several backups last night on
my home machine, so it should be good. Otherwise, I'll try around 5pm PST.

Thad

**Pull request closed without merging**
